services:
  # --- BANCO DE DADOS ÚNICO ---
  postgres:
    image: postgres:15-alpine
    container_name: shared-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      # Este arquivo será lido AUTOMATICAMENTE na primeira vez que o banco subir
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shared-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: shared-redis
    ports:
      - "6379:6379"

  # --- MICROSSERVIÇOS ---
  catalog-service:
    build: ./backend/catalog-service
    container_name: catalog-service
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_NAME=catalog_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  inventory-service:
    build: ./backend/inventory-service
    container_name: inventory-service
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=3002
      - DB_HOST=postgres
      - DB_NAME=inventory_db
      - DB_USER=admin
      - DB_PASSWORD=admin

  order-service:
    build: ./backend/order-service
    container_name: order-service
    ports:
      - "3003:3003"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=3003
      - DB_HOST=postgres
      - DB_NAME=order_db
      - DB_USER=admin
      - DB_PASSWORD=admin

  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    ports:
      - "3004:3004"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=3004
      - DB_HOST=postgres
      - DB_NAME=payment_db
      - DB_USER=admin
      - DB_PASSWORD=admin

  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "3005:3005"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=3005
      - DB_HOST=postgres
      - DB_NAME=user_db
      - DB_USER=admin
      - DB_PASSWORD=admin